local component = require("component")
local robot = require("robot")
local rs = component.redstone
local inv = component.inventory_controller
local orientation = "Z+"
local orientationNum = 1
local XCoord = 0
local YCoord = 0
local ZCoord = 0
local function SetEndOrientation(delta)
    orientationNum = orientationNum + delta
    if orientationNum == 0 then
        orientationNum = 4
        orientation = "X-"
    elseif orientationNum == 1 then
        orientation = "Z+"
    elseif orientationNum == 2 then
        orientation = "X+"
    elseif orientationNum == 3 then
        orientation = "Z-"
    elseif orientationNum == 4 then
        orientation = "X-"
    elseif orientationNum == 5 then
        orientationNum = 1
        orientation = "Z+"
    elseif orientationNum == -1 then
        orientationNum = 3
        orientation = "Z-"
    elseif orientationNum == 6 then
        orientationNum = 2
        orientation = "X+"
    end
end
local function RobotForward()
    robot.forward()
    if orientation == "Z-" then
        ZCoord = ZCoord - 1
    elseif orientation == "Z+" then
        ZCoord = ZCoord + 1
    elseif orientation == "X-" then
        XCoord = XCoord - 1
    elseif orientation == "X+" then
        XCoord = XCoord + 1
    end
end
local function RobotDown()
    robot.down()
    YCoord = YCoord - 1
end
local function RobotUp()
    robot.up()
    YCoord = YCoord + 1
end
local function RobotTurnLeft()
    robot.turnLeft()
    SetEndOrientation(-1)
end
local function RobotTurnRight()
    robot.turnRight()
    SetEndOrientation(1)
end
local function RobotTurnAround()
    robot.turnAround()
    SetEndOrientation(-2)
end
local function SetOrientation(Target)
    local TargetNum
    if Target == "Z+" then
        TargetNum = 1
    elseif Target == "X+" then
        TargetNum = 2
    elseif Target == "Z-" then
        TargetNum = 3
    elseif Target == "X-" then
        TargetNum = 4
    end
    local Diff = TargetNum - orientationNum

    if Diff == -1 or Diff == 3 then
        RobotTurnLeft()
    elseif Diff == 1 or Diff == -3 then
        RobotTurnRight()
    elseif Diff == 2 or Diff == -2 then
        RobotTurnAround()
    end
end
local function GoToX(X)
    if X < XCoord then
        SetOrientation("X-")
        while XCoord > X do
            RobotForward()
        end
    elseif X > XCoord then
        SetOrientation("X+")
        while XCoord < X do
            RobotForward()
        end
    end
end
local function GoToY(Y)
    if Y < YCoord then
        while YCoord > Y do
            RobotDown()
        end
    elseif Y > YCoord then
        while YCoord < Y do
            RobotUp()
        end
    end
end
local function GoToZ(Z)
    if Z < ZCoord then
        SetOrientation("Z-")
        while ZCoord > Z do
            RobotForward()
        end
    elseif Z > ZCoord then
        SetOrientation("Z+")
        while ZCoord < Z do
            RobotForward()
        end
    end
end
local function GoToCoords(X,Y,Z)
    GoToX(X)
    GoToZ(Z)
    GoToY(Y)
end
local function CraftLuVConveyour()
	GoToCoords(0,1,1)
	SetOrientation("Z+")
	robot.select(1)
	inv.suckFromSlot(3,1,2)
	robot.select(2)
	inv.suckFromSlot(3,2,2)
	robot.select(3)
	inv.suckFromSlot(3,3,4)
	robot.select(4)
	inv.suckFromSlot(3,4,32)
	robot.select(5)
	inv.suckFromSlot(3,5,2)
	GoToCoords(0,0,0)
	GoToCoords(0,1,-1)
	robot.select(1)
	robot.dropUp()
	GoToCoords(0,1,-2)
	robot.select(2)
	robot.dropUp()
	GoToCoords(0,1,-3)
	robot.select(3)
	robot.dropUp()
	GoToCoords(0,1,-4)
	robot.select(4)
	robot.dropUp()
	GoToCoords(0,1,-5)
	robot.select(5)
	robot.dropUp()
	GoToCoords(0,0,0)
end
local function CraftLuVMotor()
	GoToCoords(0,0,1)
	SetOrientation("Z+")
	robot.select(1)
	inv.suckFromSlot(3,1,1)
	robot.select(2)
	inv.suckFromSlot(3,2,2)
	robot.select(3)
	inv.suckFromSlot(3,3,64)
	robot.select(4)
	inv.suckFromSlot(3,4,64)
	robot.select(5)
	inv.suckFromSlot(3,5,64)
	robot.select(6)
	inv.suckFromSlot(3,6,64)
	robot.select(7)
	inv.suckFromSlot(3,7,2)
	GoToCoords(0,0,0)
	GoToCoords(0,1,-1)
	robot.select(1)
	robot.dropUp()
	GoToCoords(0,1,-2)
	robot.select(2)
	robot.dropUp()
	GoToCoords(0,1,-3)
	robot.select(3)
	robot.dropUp()
	GoToCoords(0,1,-4)
	robot.select(4)
	robot.dropUp()
	GoToCoords(0,1,-5)
	robot.select(5)
	robot.dropUp()
	GoToCoords(0,1,-6)
	robot.select(6)
	robot.dropUp()
	GoToCoords(0,1,-7)
	robot.select(7)
	robot.dropUp()
	GoToCoords(0,0,0)
end
local function CraftLuVFieldGenerator()
	GoToCoords(1,0,0)
	SetOrientation("X+")
	robot.select(1)
	inv.suckFromSlot(3,1,1)
	robot.select(2)
	inv.suckFromSlot(3,2,6)
	robot.select(3)
	inv.suckFromSlot(3,3,1)
	robot.select(4)
	inv.suckFromSlot(3,4,4)
	robot.select(5)
	inv.suckFromSlot(3,5,8)
	robot.select(10)
	inv.suckFromSlot(3,10,8)
	GoToCoords(0,0,0)
	GoToCoords(0,5,1)
	robot.select(6)
	inv.suckFromSlot(3,6,64)
	robot.select(7)
	inv.suckFromSlot(3,7,64)
	robot.select(8)
	inv.suckFromSlot(3,8,64)
	robot.select(9)
	inv.suckFromSlot(3,9,64)
	GoToCoords(0,0,0)
	GoToCoords(0,1,-1)
	robot.select(1)
	robot.dropUp()
	GoToCoords(0,1,-2)
	robot.select(2)
	robot.dropUp()
	GoToCoords(0,1,-3)
	robot.select(3)
	robot.dropUp()
	GoToCoords(0,1,-4)
	robot.select(4)
	robot.dropUp()
	GoToCoords(0,1,-5)
	robot.select(5)
	robot.dropUp()
	GoToCoords(0,1,-6)
	robot.select(6)
	robot.dropUp()
	GoToCoords(0,1,-7)
	robot.select(7)
	robot.dropUp()
	GoToCoords(0,1,-8)
	robot.select(8)
	robot.dropUp()
	GoToCoords(0,1,-9)
	robot.select(9)
	robot.dropUp()
	GoToCoords(0,1,-10)
	robot.select(10)
	robot.dropUp()
	GoToCoords(0,0,0)
end
local function CraftLuVPiston()
	GoToCoords(0,3,1)
	SetOrientation("Z+")
	robot.select(1)
	inv.suckFromSlot(3,1,1)
	robot.select(2)
	inv.suckFromSlot(3,2,6)
	robot.select(3)
	inv.suckFromSlot(3,3,4)
	robot.select(4)
	inv.suckFromSlot(3,4,32)
	robot.select(5)
	inv.suckFromSlot(3,5,4)
	robot.select(6)
	inv.suckFromSlot(3,6,1)
	robot.select(7)
	inv.suckFromSlot(3,7,2)
	robot.select(8)
	inv.suckFromSlot(3,8,4)
	GoToCoords(0,0,0)
	GoToCoords(0,1,-1)
	robot.select(1)
	robot.dropUp()
	GoToCoords(0,1,-2)
	robot.select(2)
	robot.dropUp()
	GoToCoords(0,1,-3)
	robot.select(3)
	robot.dropUp()
	GoToCoords(0,1,-4)
	robot.select(4)
	robot.dropUp()
	GoToCoords(0,1,-5)
	robot.select(5)
	robot.dropUp()
	GoToCoords(0,1,-6)
	robot.select(6)
	robot.dropUp()
	GoToCoords(0,1,-7)
	robot.select(7)
	robot.dropUp()
	GoToCoords(0,1,-8)
	robot.select(8)
	robot.dropUp()
	GoToCoords(0,0,0)
end
local function CraftLuVPump()
	GoToCoords(0,2,1)
	SetOrientation("Z+")
	robot.select(1)
	inv.suckFromSlot(3,1,1)
	robot.select(2)
	inv.suckFromSlot(3,2,2)
	robot.select(3)
	inv.suckFromSlot(3,3,2)
	robot.select(4)
	inv.suckFromSlot(3,4,8)
	robot.select(5)
	inv.suckFromSlot(3,5,4)
	robot.select(6)
	inv.suckFromSlot(3,6,2)
	robot.select(7)
	inv.suckFromSlot(3,7,2)
	robot.select(8)
	inv.suckFromSlot(3,8,1)
	GoToCoords(0,0,0)
	GoToCoords(0,1,-1)
	robot.select(1)
	robot.dropUp()
	GoToCoords(0,1,-2)
	robot.select(2)
	robot.dropUp()
	GoToCoords(0,1,-3)
	robot.select(3)
	robot.dropUp()
	GoToCoords(0,1,-4)
	robot.select(4)
	robot.dropUp()
	GoToCoords(0,1,-5)
	robot.select(5)
	robot.dropUp()
	GoToCoords(0,1,-6)
	robot.select(6)
	robot.dropUp()
	GoToCoords(0,1,-7)
	robot.select(7)
	robot.dropUp()
	GoToCoords(0,0,-4)
	SetOrientation("X+")
	robot.select(8)
	robot.drop()
	GoToCoords(0,0,0)
end
local function CraftLuVRobotArm()

	GoToCoords(0,4,1)
	robot.select(1)
	inv.suckFromSlot(3,1,4)
	robot.select(2)
	inv.suckFromSlot(3,2,1)
	robot.select(3)
	inv.suckFromSlot(3,3,3)
	robot.select(4)
	inv.suckFromSlot(3,4,2)
	robot.select(5)
	inv.suckFromSlot(3,5,1)
	robot.select(6)
	inv.suckFromSlot(3,6,2)
	robot.select(7)
	inv.suckFromSlot(3,7,2)
	robot.select(8)
	inv.suckFromSlot(3,8,6)
	robot.select(9)
	inv.suckFromSlot(3,9,6)
	GoToCoords(0,0,0)
	GoToCoords(0,1,-1)
	robot.select(1)
	robot.dropUp()
	GoToCoords(0,1,-2)
	robot.select(2)
	robot.dropUp()
	GoToCoords(0,1,-3)
	robot.select(3)
	robot.dropUp()
	GoToCoords(0,1,-4)
	robot.select(4)
	robot.dropUp()
	GoToCoords(0,1,-5)
	robot.select(5)
	robot.dropUp()
	GoToCoords(0,1,-6)
	robot.select(6)
	robot.dropUp()
	GoToCoords(0,1,-7)
	robot.select(7)
	robot.dropUp()
	GoToCoords(0,1,-8)
	robot.select(8)
	robot.dropUp()
	GoToCoords(0,1,-9)
	robot.select(9)
	robot.dropUp()
	GoToCoords(0,0,0)
end
local function CraftLuVEmitter()
	GoToCoords(-1,0,0)
	SetOrientation("X-")
	robot.select(1)
	inv.suckFromSlot(1)
	robot.select(2)
	inv.suckFromSlot(1)
	robot.select(3)
	inv.suckFromSlot(2)
	robot.select(4)
	inv.suckFromSlot(4)
	robot.select(5)
	inv.suckFromSlot(7)
	robot.select(6)
	inv.suckFromSlot(64)
	robot.select(7)
	inv.suckFromSlot(64)
	robot.select(8)
	inv.suckFromSlot(64)
	robot.select(9)
	inv.suckFromSlot(7)
	GoToCoords(0,0,0)
	GoToCoords(0,1,-1)
	robot.select(1)
	robot.dropUp()
	GoToCoords(0,1,-2)
	robot.select(2)
	robot.dropUp()
	GoToCoords(0,1,-3)
	robot.select(3)
	robot.dropUp()
	GoToCoords(0,1,-4)
	robot.select(4)
	robot.dropUp()
	GoToCoords(0,1,-5)
	robot.select(5)
	robot.dropUp()
	GoToCoords(0,1,-6)
	robot.select(6)
	robot.dropUp()
	GoToCoords(0,1,-7)
	robot.select(7)
	robot.dropUp()
	GoToCoords(0,1,-8)
	robot.select(8)
	robot.dropUp()
	GoToCoords(0,1,-9)
	robot.select(9)
	robot.dropUp()
	GoToCoords(0,0,0)
end
local function CraftLuVSensor()
	GoToCoords(1,1,0)
	SetOrientation("X+")
	robot.select(1)
	inv.suckFromSlot(3,1,1)
	robot.select(2)
	inv.suckFromSlot(3,2,1)
	robot.select(3)
	inv.suckFromSlot(3,3,2)
	robot.select(4)
	inv.suckFromSlot(3,4,4)
	robot.select(5)
	inv.suckFromSlot(3,5,7)
	robot.select(6)
	inv.suckFromSlot(3,6,64)
	robot.select(7)
	inv.suckFromSlot(3,7,64)
	robot.select(8)
	inv.suckFromSlot(3,8,64)
	robot.select(9)
	inv.suckFromSlot(3,9,7)
	GoToCoords(0,0,0)
	GoToCoords(0,1,-1)
	robot.select(1)
	robot.dropUp()
	GoToCoords(0,1,-2)
	robot.select(2)
	robot.dropUp()
	GoToCoords(0,1,-3)
	robot.select(3)
	robot.dropUp()
	GoToCoords(0,1,-4)
	robot.select(4)
	robot.dropUp()
	GoToCoords(0,1,-5)
	robot.select(5)
	robot.dropUp()
	GoToCoords(0,1,-6)
	robot.select(6)
	robot.dropUp()
	GoToCoords(0,1,-7)
	robot.select(7)
	robot.dropUp()
	GoToCoords(0,1,-8)
	robot.select(8)
	robot.dropUp()
	GoToCoords(0,1,-9)
	robot.select(9)
	robot.dropUp()
	GoToCoords(0,0,0)
end
local function CraftSolarPanelTier1()
	GoToCoords(1,2,0)
	SetOrientation("X+")
	robot.select(1)
	inv.suckFromSlot(3,1,3)
	robot.select(2)
	inv.suckFromSlot(3,2,2)
	robot.select(3)
	inv.suckFromSlot(3,3,1)
	robot.select(4)
	inv.suckFromSlot(3,4,2)
	robot.select(5)
	inv.suckFromSlot(3,5,1)
	GoToCoords(0,0,0)
	GoToCoords(0,1,-1)
	robot.select(1)
	robot.dropUp()
	GoToCoords(0,1,-2)
	robot.select(2)
	robot.dropUp()
	GoToCoords(0,1,-3)
	robot.select(3)
	robot.dropUp()
	GoToCoords(0,1,-4)
	robot.select(4)
	robot.dropUp()
	GoToCoords(0,1,-5)
	robot.select(5)
	robot.dropUp()
	GoToCoords(0,0,0)
end
local function CraftSolarPanelTier2()
	GoToCoords(1,3,0)
	SetOrientation("X+")
	robot.select(1)
	inv.suckFromSlot(3,1,1)
	robot.select(2)
	inv.suckFromSlot(3,2,4)
	robot.select(3)
	inv.suckFromSlot(3,3,1)
	robot.select(4)
	inv.suckFromSlot(3,4,2)
	robot.select(5)
	inv.suckFromSlot(3,5,2)
	GoToCoords(0,0,0)
	GoToCoords(0,1,-1)
	robot.select(1)
	robot.dropUp()
	GoToCoords(0,1,-2)
	robot.select(2)
	robot.dropUp()
	GoToCoords(0,1,-3)
	robot.select(3)
	robot.dropUp()
	GoToCoords(0,1,-4)
	robot.select(4)
	robot.dropUp()
	GoToCoords(0,1,-5)
	robot.select(5)
	robot.dropUp()
	GoToCoords(0,0,0)
end
local function CraftSolarPanelTier3()
	GoToCoords(1,4,0)
	SetOrientation("X+")
	robot.select(1)
	inv.suckFromSlot(3,1,1)
	robot.select(2)
	inv.suckFromSlot(3,2,4)
	robot.select(3)
	inv.suckFromSlot(3,3,3)
	robot.select(4)
	inv.suckFromSlot(3,4,1)
	robot.select(5)
	inv.suckFromSlot(3,5,2)
	GoToCoords(0,0,0)
	GoToCoords(0,1,-1)
	robot.select(1)
	robot.dropUp()
	GoToCoords(0,1,-2)
	robot.select(2)
	robot.dropUp()
	GoToCoords(0,1,-3)
	robot.select(3)
	robot.dropUp()
	GoToCoords(0,1,-4)
	robot.select(4)
	robot.dropUp()
	GoToCoords(0,1,-5)
	robot.select(5)
	robot.dropUp()
	GoToCoords(0,0,0)
end
local function CraftSolarPanelTier4()
	GoToCoords(1,5,0)
	SetOrientation("X+")
	robot.select(1)
	inv.suckFromSlot(3,1,4)
	robot.select(2)
	inv.suckFromSlot(3,2,1)
	robot.select(3)
	inv.suckFromSlot(3,3,2)
	robot.select(4)
	inv.suckFromSlot(3,4,1)
	robot.select(5)
	inv.suckFromSlot(3,5,2)
	robot.select(6)
	inv.suckFromSlot(3,6,1)
	GoToCoords(0,0,0)
	GoToCoords(0,1,-1)
	robot.select(1)
	robot.dropUp()
	GoToCoords(0,1,-2)
	robot.select(2)
	robot.dropUp()
	GoToCoords(0,1,-3)
	robot.select(3)
	robot.dropUp()
	GoToCoords(0,1,-4)
	robot.select(4)
	robot.dropUp()
	GoToCoords(0,1,-5)
	robot.select(5)
	robot.dropUp()
	GoToCoords(0,1,-6)
	robot.select(6)
	robot.dropUp()
	GoToCoords(0,0,0)
end
while true do
    for i = 4980, 4990 do
		rs.setWirelessFrequency(i)
		result = rs.getWirelessInput()
		if i == 4980 and result then
			CraftLuVFieldGenerator()
		elseif i == 4981 and result then
			CraftLuVSensor()
		elseif i == 4982 and result then
			CraftSolarPanelTier1()
		elseif i == 4983 and result then
			CraftSolarPanelTier2()
		elseif i == 4984 and result then
			CraftSolarPanelTier3()
		elseif i == 4985 and result then
			CraftSolarPanelTier4()
		elseif i == 4986 and result then
			CraftLuVMotor()
		elseif i == 4987 and result then
			CraftLuVConveyour()
		elseif i == 4988 and result then
			CraftLuVPump()
		elseif i == 4989 and result then
			CraftLuVPiston()
		elseif i == 4990 and result then
			CraftLuVRobotArm()
		elseif i == 4991 and result then
			CraftLuVEmitter()
		end
	end
    os.sleep(5)
end